title: Andréa Duque
author: Andréa Duque
description: Thoughts on applied AI, ML, Agents and the cloud.
baseurl: "/andrea-tech-notes"
url: "https://andreabrduque.github.io"

theme: minima

markdown: kramdown
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed

minima:
  skin: classic
