title: Andréa Duque
author: Andréa Duque
description: Andréa's thoughts on applied AI/ML, cloud native systems, and agentic AI.
baseurl: "/andrea-tech-notes"
url: "https://andreabrduque.github.io"

theme: minima

markdown: kramdown
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed

minima:
  skin: classic
